dataset:
  path: ${hydra:runtime.cwd}/data/train.csv
  features: ["mana", "attack", "health"]
  target: "strategy"

machine_learning:
  path: ${hydra:runtime.cwd}/models/card_analyzer.pkl
  model:
    _target_: sklearn.ensemble.RandomForestClassifier
    bootstrap: True
    max_depth: 10
    max_features: "sqrt"
    min_samples_leaf: 1
    min_samples_split: 5
    n_estimators: 100
    n_jobs: -1
    random_state: 22
  metric:
    _target_: sklearn.metrics.roc_auc_score